### ISSUE TITLE
pitas_io not found

### ISSUE THREAD

**Issue by msyriac** [dwhan89/pitas#2]
... when I try to run the test script:
https://github.com/dwhan89/pitas/blob/master/test/simple_test.py#L16

**Comment by dwhan89** [comment]
Hmm, this is strange. I just checked, and this file is already on master branch. Are there any other error message you get?

**Comment by msyriac** [comment]
Those import statements in pitas/__init__.py might not be python 3 compatible. In general, I'm running in to python 3 compatibility issues. Let me see if I can fix these.

**Comment by dwhan89** [comment]
It should be fixed with python 3 compatibility patch. Closing the issue
